#!/usr/bin/env python

import rospy
from styx_msgs.msg import Lane, Waypoint
from waypoint_locator.srv import *
import tf
import numpy as np
import math
from scipy.spatial import cKDTree

# a reasonable maximum distance between the current pose and
# reference waypoints.
MAX_DIST = 300

class WaypointLocator(object):
    def __init__(self):
        rospy.init_node('waypoint_locator')

        self.all_ref_waypoints = []
        self.kdtree = None
        
        rospy.Service('~locate_waypoints_around', LocateWaypointsAround, self.locate_waypoints_around)

        # subscribe to /base_waypoints to get the waypoints information
        rospy.Subscriber('/base_waypoints', Lane, self.waypoints_cb, queue_size=1)
        
        rospy.spin()

    def locate_waypoints_around(self, req):
        # use kdtree for looking up the closest waypoint
        # the closest waypoint may be either behind or ahead of the querying pose
        # so looking up one waypoint back and one waypoint forward and
        # determine.

        num_all_ref_waypoints = len(self.all_ref_waypoints)
        
        if self.kdtree is None or num_all_ref_waypoints == 0:
            return LocateWaypointsAroundResponse(-1, -1)

        _, closest_index = self.kdtree.query((req.pose.position.x, req.pose.position.y))

        i, j, k = closest_index - 1, closest_index, closest_index + 1
        if i < 0:
            i += num_all_ref_waypoints
        if k >= num_all_ref_waypoints:
            k -= num_all_ref_waypoints 

        v_j_i = (self.all_ref_waypoints[i].pose.pose.position.x - self.all_ref_waypoints[j].pose.pose.position.x,
                 self.all_ref_waypoints[i].pose.pose.position.y - self.all_ref_waypoints[j].pose.pose.position.y)
        v_j_k = (self.all_ref_waypoints[k].pose.pose.position.x - self.all_ref_waypoints[j].pose.pose.position.x,
                 self.all_ref_waypoints[k].pose.pose.position.y - self.all_ref_waypoints[j].pose.pose.position.y)
        v_j_p = (req.pose.position.x - self.all_ref_waypoints[j].pose.pose.position.x,
                 req.pose.position.y - self.all_ref_waypoints[j].pose.pose.position.y)
        ca1 = self.get_cos_angle_between(v_j_p, v_j_i)
        ca2 = self.get_cos_angle_between(v_j_p, v_j_k)

        nearest, behind, ahead = (ca1 > ca2) and (j, i, j) or (j, j, k)
        return LocateWaypointsAroundResponse(nearest, behind, ahead)

    def waypoints_cb(self, waypoints):
        all_ref_waypoints = []
        waypoints = waypoints.waypoints
        xy_pairs = []
        for waypoint in waypoints:
            all_ref_waypoints.append(waypoint)
            xy_pairs.append((waypoint.pose.pose.position.x, waypoint.pose.pose.position.y))
        self.kdtree = cKDTree(xy_pairs)
        self.all_ref_waypoints = all_ref_waypoints
        rospy.loginfo("Base waypoints received. WaypointLocator service ready.")

    def get_cos_angle_between(self, v1, v2):
        return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

if __name__ == '__main__':
    try:
        WaypointLocator()
    except rospy.ROSInterruptException:
        pass
