#!/usr/bin/env python

import rospy
import math
import tf
import numpy as np
from visualization_msgs.msg import Marker, MarkerArray
from std_msgs.msg import Header
from geometry_msgs.msg import Point, Quaternion, PoseStamped
from styx_msgs.msg import Lane, Waypoint
from nav_msgs.msg import Path
from waypoint_locator.srv import *

class Viz(object):
    def __init__(self):
        rospy.init_node('viz')
        
        # storage for all the waypoints
        self.all_ref_waypoints = []

        self.current_pose = None

        # storing current path
        self.current_path = None

        # remember waypoints index behind and ahead of the last
        # current_pose, so for the next round we can save the time for
        # looking
        self.pose_ref_waypoints_idx = None

        self.locate_waypoints_around = rospy.ServiceProxy('/waypoint_locator/locate_waypoints_around', LocateWaypointsAround)

        rospy.Subscriber('/current_pose', PoseStamped, self.pose_cb, queue_size=1)
        rospy.Subscriber('/base_waypoints', Lane, self.waypoints_cb, queue_size=1)
        rospy.Subscriber('/final_waypoints', Lane, self.final_waypoints_cb, queue_size=1)

        self.viz_current_pub = rospy.Publisher('viz_current_pose', PoseStamped, queue_size=1)
        self.viz_waypoints_around_pub = rospy.Publisher('viz_waypoints_around', Marker, queue_size=1)
        self.viz_current_path_pub = rospy.Publisher('viz_current_path', Path, queue_size=1)

        rospy.wait_for_service('/waypoint_locator/locate_waypoints_around')

        rate = rospy.Rate(30)
        while not rospy.is_shutdown():
            if len(self.all_ref_waypoints) > 0:
                self.publish_current()
                self.publish_waypoints_around()
                self.publish_current_path()
            rate.sleep()

    def final_waypoints_cb(self, msg):
        current_path = Path()
        current_path.header = Header()
        current_path.header.stamp = rospy.Time.now()
        current_path.header.frame_id = "/world"
        current_path.poses = []
        waypoints = msg.waypoints
        # thresholding the number of final waypoints
        waypoints_thresh = 50
        counter = 0
        for wp in waypoints:
            position = wp.pose.pose.position
            orientation = wp.pose.pose.orientation
            current_path.poses.append(
                self.get_pose_stamped(position, orientation))
            counter += 1
            if counter > waypoints_thresh:
                break
        self.current_path = current_path

    def pose_cb(self, msg):
        self.current_pose = msg

        req = LocateWaypointsAroundRequest(msg.pose)
        resp = self.locate_waypoints_around(req)
        if resp.behind >= 0 and resp.ahead >= 0:
            self.pose_ref_waypoints_idx = (resp.behind, resp.ahead)
        else:
            self.pose_ref_waypoints_idx = None

    def publish_current_path(self):
        if self.current_path is None:
            return

        self.viz_current_path_pub.publish(self.current_path)

    def publish_current(self):
        if self.current_pose is None:
            return
        
        msg_copy = PoseStamped()
        msg_copy.header = Header()
        msg_copy.header.stamp = rospy.Time.now()
        msg_copy.header.frame_id = "/world"
        
        msg_copy.pose.position.x = self.current_pose.pose.position.x
        msg_copy.pose.position.y = self.current_pose.pose.position.y
        msg_copy.pose.position.z = self.current_pose.pose.position.z

        msg_copy.pose.orientation.x = self.current_pose.pose.orientation.x
        msg_copy.pose.orientation.y = self.current_pose.pose.orientation.y
        msg_copy.pose.orientation.z = self.current_pose.pose.orientation.z
        msg_copy.pose.orientation.w = self.current_pose.pose.orientation.w
                
        self.viz_current_pub.publish(msg_copy)

    def publish_waypoints_around(self):
        """Visualizing reference waypoints by publishing visualization_msgs/Marker."""
        if self.pose_ref_waypoints_idx is None:
            return

        # visualizing +/- 5 waypoints around the reference waypoints.
        num = 5
        msg = Marker()
        msg.points = []
        msg.header = Header()
        msg.header.stamp = rospy.Time.now()
        msg.header.frame_id = "/world"
        msg.id = 1
        msg.type = Marker.SPHERE_LIST
        msg.ns = "/viz_waypoints"
        msg.action = Marker.ADD # or MODIFY. Both are 0
        
        msg.scale.x = 0.1
        msg.scale.y = 0.1
        msg.scale.z = 0.1
                
        msg.color.r = 0.0
        msg.color.g = 1.0
        msg.color.b = 0.0
        msg.color.a = 0.8
        
        wp_types = ['behind', 'ahead']
        # waypoints behind
        for t in wp_types:
            if t == 'behind':
                r = range(num, -1, -1)
            else:
                r = range(num + 1)

            for i in r:
                if t == 'behind':
                    ref_idx = self.pose_ref_waypoints_idx[0] - i
                else:
                    ref_idx = self.pose_ref_waypoints_idx[1] + i

                ref_idx = ref_idx % len(self.all_ref_waypoints)
                wp = self.all_ref_waypoints[ref_idx]
                
                # marker pose, scale and color
                msg.points.append(Point(wp.pose.pose.position.x,
                                        wp.pose.pose.position.y,
                                        wp.pose.pose.position.z))
        self.viz_waypoints_around_pub.publish(msg)
            
    def dist(self, pose, wp):
        a = pose.pose.position
        b = wp.pose.pose.position
        return math.sqrt((a.x - b.x) ** 2 + (a.y - b.y) ** 2 + (a.z - b.z) ** 2)

    def waypoints_cb(self, waypoints):
        self.all_ref_waypoints = []
        waypoints = waypoints.waypoints
        for waypoint in waypoints:
            self.all_ref_waypoints.append(waypoint)
        print("Base waypoints received")

    def get_pose_stamped(self, position, orientation):
        msg = PoseStamped()
        msg.header = Header()
        msg.header.stamp = rospy.Time.now()
        msg.header.frame_id = "/world"

        msg.pose.position = Point(position.x, position.y, position.z)
        msg.pose.orientation = Quaternion(orientation.x, orientation.y, orientation.z, orientation.w)
        return msg

if __name__ == '__main__':
    try:
        Viz()
    except rospy.ROSInterruptException:
        pass
